version: "3.9"

networks:
  services-network:

services:

  # ==========================================
  # EUREKA SERVER
  # ==========================================
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: ${EUREKA_NAME}
    networks:
      - services-network
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    environment:
      EUREKA_PORT: ${EUREKA_PORT}
#    healthcheck:
#      test: ["CMD", "curl", "-f-", "http://localhost:8761/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  # ==========================================
  # GATEWAY
  # ==========================================
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: ${GATEWAY_NAME}
    depends_on:
      eureka:
        condition: service_started
    networks:
      - services-network
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://${EUREKA_NAME}:8761/eureka"
      SERVER_PORT: ${GATEWAY_PORT}
      GATEWAY_IDENTITY_BASE_URI: "http://localhost:${GATEWAY_PORT}/api/auth"
      GATEWAY_IDENTITY_CLIENT_ID: web-client

  # ==========================================
  # IDENTIFY SERVICE
  # ==========================================
  identify:
    build:
      context: ./identify
      dockerfile: Dockerfile
    container_name: ${IDENTIFY_NAME}
    depends_on:
      eureka:
        condition: service_started
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - services-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://${EUREKA_NAME}:8761/eureka"

      SPRING_DATASOURCE_URL: "jdbc:mysql://${DB_CONTAINER}:${DB_PORT}/${DB_IDENTIFY_NAME}${DB_PARAMETERS}"
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: ${REDIS_CONTAINER}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

      SPRING_RABBITMQ_HOST: ${RABBIT_CONTAINER}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      EMAIL_NAME: ${EMAIL_NAME}
      EMAIL_PASS_CODE: ${EMAIL_PASS_CODE}

  # ==========================================
  # USER SERVICE
  # ==========================================

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: ${USER_SERVICE_NAME}
    depends_on:
      eureka:
        condition: service_started
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - services-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://${EUREKA_NAME}:8761/eureka"

      SPRING_DATASOURCE_URL: "jdbc:mysql://${DB_CONTAINER}:${DB_PORT}/${DB_IDENTIFY_NAME}${DB_PARAMETERS}"
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: ${REDIS_CONTAINER}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

      SPRING_RABBITMQ_HOST: ${RABBIT_CONTAINER}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}

  # ==========================================
  # NOTIFICATION SERVICE
  # ==========================================
  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: ${NOTIFICATION_NAME}
    depends_on:
      eureka:
        condition: service_started
      rabbit:
        condition: service_healthy
    networks:
      - services-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://${EUREKA_NAME}:8761/eureka"
      SPRING_RABBITMQ_HOST: ${RABBIT_CONTAINER}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
      EMAIL_NAME: ${EMAIL_NAME}
      EMAIL_PASS_CODE: ${EMAIL_PASS_CODE}


  # ==========================================
  # RABBITMQ
# ==========================================
  rabbit:
    image: rabbitmq:3-management
    container_name: ${RABBIT_CONTAINER}
    networks:
      - services-network
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MGMT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # REDIS
  # ==========================================
  redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER}
    networks:
      - services-network
    ports: ["${REDIS_PORT}:6379"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # MYSQL
  # ==========================================
  mysql:
    image: mysql:8
    container_name: ${DB_CONTAINER}
    networks:
      - services-network
    # jeśli nie chcesz wystawiać MySQL poza dockera → usuń ports całkowicie
    ports:
      - "${DB_PORT}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_IDENTIFY_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


################################gui
  # ==========================================
  # REDIS GUI — RedisInsight
  # ==========================================
  redis-gui:
    image: redis/redisinsight:latest
    container_name: redis-insight
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - services-network
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data

  # ==========================================
  # MYSQL GUI — phpMyAdmin
  # ==========================================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - services-network
    ports:
      - "13306:80"
    environment:

      PMA_HOST: ${DB_CONTAINER}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}

      UPLOAD_LIMIT: 1024M


volumes:
  redisinsight-data:
