spring:
  rabbitmq:
    host: localhost
    port: 13001
    username: guest
    password: guest
    listener:
      simple:
        # Automatic acknowledgment mode
        acknowledge-mode: auto
        # Number of concurrent consumers
        concurrency: 1
        max-concurrency: 5
        # Retry configuration
        retry:
          enabled: true
          initial-interval: 3000  # 3 seconds
          max-attempts: 3
          max-interval: 10000     # 10 seconds
          multiplier: 2.0
  application:
    name: identity-service
  data:
    redis:
      host: localhost
      port: 7890
      password: ""      # jeśli nie masz hasła → zostaw puste lub usuń linię
      timeout: 5000ms

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

  datasource:
    url: jdbc:mysql://localhost:3306/identitydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false



#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:}
#      timeout: 2000ms
#      jedis:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: -1ms
#
#  cache:
#    type: redis
#    redis:
#      time-to-live: 900000

jwt:
  secret: lg8UfAf4xZ3y1NEREOl7FS6E4T72ZxWiVHXnpandIva8bpfCTlXZSWBMYHGhon3CMmkHTr9dAA1bYfditkYJ39
  access-token-expiration: 3600000
  refresh-secret: ${JWT_REFRESH_SECRET:different-refresh-secret-key-must-be-different-from-access-secret-at-least-512-bits}
  refresh-token-expiration: 86400000

activation:
  code-ttl-minutes: 15

server:
  port: 12001

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:12100/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.polibuda.footballclub.identify: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.redis: INFO

