spring:
  application:
    name: notification-service
#  data:
#    redis:
#      host: ${REDIS_CONTAINER:localhost}
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:}
#      timeout: 5000ms

  rabbitmq:
    host: ${RABBIT_CONTAINER:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    listener:
      simple:
        # Automatic acknowledgment mode
        acknowledge-mode: auto
        # Number of concurrent consumers
        concurrency: 1
        max-concurrency: 5
        # Retry configuration
        retry:
          enabled: true
          initial-interval: 3000  # 3 seconds
          max-attempts: 3
          max-interval: 10000     # 10 seconds
          multiplier: 2.0

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_NAME:dkkd3046@gmail.com}
    password: ${EMAIL_PASS_CODE:}#tu daj kod
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
        transport:
          protocol: smtp
    default-encoding: UTF-8

server:
  port: ${NOTIFICATION_PORT:12003}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_NAME:localhost}:${EUREKA_PORT:8761}/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.polibuda.footballclub.notification: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.redis: INFO


# Email Configuration (custom properties)
email:
  from: ${EMAIL_NAME:dkkd3046@gmail.com}
  from-name: Football Club System





